version: 1
allow:
  depOnAnyVendor: false

exclude:
  - docs
  - test
  - vendor
excludeFiles:
  - "^.*_test\\.go$"

vendors:
  go-modfile:
    in: golang.org/x/mod/modfile
  3rd-cobra:
    in: github.com/spf13/cobra
  3rd-yaml:
    in: github.com/goccy/go-yaml
  3rd-yaml-parser:
    in: github.com/goccy/go-yaml/parser
  3rd-color-fmt:
    in: github.com/logrusorgru/aurora/v3
  3rd-chroma-formatters:
    in: github.com/alecthomas/chroma/formatters
  3rd-chroma-lexers:
    in: github.com/alecthomas/chroma/lexers
  3rd-chroma-styles:
    in: github.com/alecthomas/chroma/styles

components:
  main:
    in: /
  container:
    in: internal/app/internal/container/**
  app:
    in: internal/app

  commands:
    in: internal/commands/*

  glue:
    in: internal/glue/**
  glueCode:
    in: internal/glue/code
  glueProject:
    in: internal/glue/project/**
  gluePrinter:
    in: internal/glue/printer
  glueSpec:
    in: internal/glue/spec/**
  glueYamlSpec:
    in: internal/glue/yaml/spec
  glueYaml:
    in: internal/glue/yaml/*

  models:
    in: internal/models/**
  services:
    in: internal/services/*
  version:
    in: internal/version
  view:
    in: internal/view

commonComponents:
  - models

deps:
  main:
    mayDependOn:
      - app

  container:
    anyProjectDeps: true
    anyVendorDeps: true

  app:
    mayDependOn:
      - container
      - version

  commands:
    canUse:
      - 3rd-cobra

  glueSpec:
    mayDependOn:
      - glueYamlSpec

  glueYaml:
    mayDependOn:
      - glueYamlSpec
    canUse:
      - 3rd-yaml
      - 3rd-yaml-parser

  glueYamlSpec:
    canUse:
      - 3rd-yaml
      - 3rd-yaml-parser

  glueProject:
    canUse:
      - go-modfile

  gluePrinter:
    canUse:
      - 3rd-color-fmt

  glueCode:
    canUse:
      - 3rd-chroma-formatters
      - 3rd-chroma-lexers
      - 3rd-chroma-styles