version: 1

allow:
  depOnAnyVendor: false

exclude:
  - docs
  - test
  - vendor

excludeFiles:
  - "^.*_test\\.go$"

vendors:
  go-modfile:
    in: golang.org/x/mod/modfile
  3rd-cobra:
    in: github.com/spf13/cobra
  3rd-yaml:
    in: github.com/goccy/go-yaml
  3rd-yaml-parser:
    in: github.com/goccy/go-yaml/parser
  3rd-color-fmt:
    in: github.com/logrusorgru/aurora/v3
  3rd-chroma-formatters:
    in: github.com/alecthomas/chroma/formatters
  3rd-chroma-lexers:
    in: github.com/alecthomas/chroma/lexers
  3rd-chroma-styles:
    in: github.com/alecthomas/chroma/styles

components:
  main:
    in: /

  container:
    in: internal/app/internal/container/**

  app:
    in: internal/app

  commands:
    in: internal/commands/*

  glue_checker:
    in: internal/glue/checker

  glue_code:
    in: internal/glue/code

  glue_path:
    in: internal/glue/path

  glue_printer:
    in: internal/glue/printer

  glue_project:
    in: internal/glue/project

  glue_render:
    in: internal/glue/render

  glue_spec:
    in: internal/glue/spec/**

  glue_yaml_spec:
    in: internal/glue/yaml/spec

  glue_yaml:
    in: internal/glue/yaml/*

  models:
    in: internal/models/**

  services:
    in: internal/services/*

  version:
    in: internal/version

  view:
    in: internal/view

commonComponents:
  - models

deps:
  main:
    mayDependOn:
      - app

  container:
    anyProjectDeps: true
    anyVendorDeps: true

  app:
    mayDependOn:
      - container
      - version

  commands:
    canUse:
      - go-modfile
      - 3rd-cobra

  glue_spec:
    mayDependOn:
      - glue_yaml_spec

  glue_yaml:
    mayDependOn:
      - glue_yaml_spec
    canUse:
      - 3rd-yaml
      - 3rd-yaml-parser

  glue_yaml_spec:
    canUse:
      - 3rd-yaml
      - 3rd-yaml-parser

  glue_printer:
    canUse:
      - 3rd-color-fmt

  glue_code:
    canUse:
      - 3rd-chroma-formatters
      - 3rd-chroma-lexers
      - 3rd-chroma-styles