version: 1

# ------------------------------------------------------------------
# Global settings
# ------------------------------------------------------------------
allow:
  depOnAnyVendor: false

# ------------------------------------------------------------------
# Excluded folders from analyse
# ------------------------------------------------------------------
exclude:
  - vendor
  - examples
  - docs
  - checker/test

# ------------------------------------------------------------------
# Excluded files by regexp mask
# ------------------------------------------------------------------
excludeFiles:
  - "^.*_test\\.go$"

# ------------------------------------------------------------------
# Vendor libs
# ------------------------------------------------------------------
vendors:
  cobra:
    in: github.com/spf13/cobra

# ------------------------------------------------------------------
# Project components
#
# Used for split real modules and packages to abstract thing
# ------------------------------------------------------------------
components:
  main:
    in: .

  cmd:
    in: cmd

  container:
    in: cmd/container

# ------------------------------------------------------------------
# All components can import any packages from "common" list
# ------------------------------------------------------------------
commonComponents:

# ------------------------------------------------------------------
# All components can import any vendors from "common" list
# ------------------------------------------------------------------
commonVendors:

# ------------------------------------------------------------------
# Dependency rules
# ------------------------------------------------------------------
deps:
  main:
    mayDependOn:
      - cmd

  cmd:
    mayDependOn:
      - container
    canUse:
      - cobra

  container:
    anyProjectDeps: true