version: 3
workdir: internal
allow:
  depOnAnyVendor: false

exclude:
  - ./glue/deepscan/test

excludeFiles:
  - "^.*_test\\.go$"
  - "^.*\/test\/.*$"

vendors:
  go-common:           { in: golang.org/x/sync/errgroup }
  go-ast:              { in: [ golang.org/x/mod/modfile, golang.org/x/tools/go/packages ] }
  mod-term:            { in: github.com/fe3dback/span-terminal }
  3rd-cobra:           { in: github.com/spf13/cobra }
  3rd-color-fmt:       { in: github.com/logrusorgru/aurora/v3 }
  3rd-code-highlight:  { in: github.com/alecthomas/chroma/* }
  3rd-json-scheme:     { in: github.com/xeipuuv/gojsonschema }
  3rd-yaml:            { in: [ github.com/goccy/go-yaml, github.com/goccy/go-yaml/parser ] }
  3rd-graph:           { in: oss.terrastruct.com/d2/** }

components:
  main:                { in: app }
  container:           { in: app/internal/container/** }
  operations:          { in: operations/* }
  services:            { in: services/** }
  view:                { in: view }
  models:              { in: models/** }

commonVendors:
  - go-common
  - mod-term

commonComponents:
  - models

deps:
  main:
    mayDependOn:
      - container

  container:
    anyProjectDeps: true
    anyVendorDeps: true

  operations:
    mayDependOn:
      - services
      - view
    canUse:
      - 3rd-graph

  services:
    mayDependOn:
      - services
    canUse:
      - go-ast
      - 3rd-yaml
      - 3rd-color-fmt
      - 3rd-code-highlight
      - 3rd-json-scheme
